# EDA

In this simplified EDA following questions are answered

* Dimensions: amount of columns and rows 

* Datatypes: numeric, categorigal, dates, text?

* missing values (missing data) 

* Duplicated rows

* Numereric values

In [44]:
import pandas as pd
from backend.constants import DATA_PATH

## SOLAR DATASET

In [ ]:

solar_df = pd.read_csv(DATA_PATH/"solar.csv")

solar_df

In [46]:
solar_df.shape

(11898, 15)

In [47]:
solar_df.dtypes

Catalog Number         int64
Calendar Date            str
Eclipse Time             str
Delta T (s)            int64
Lunation Number        int64
Saros Number           int64
Eclipse Type             str
Gamma                float64
Eclipse Magnitude    float64
Latitude                 str
Longitude                str
Sun Altitude           int64
Sun Azimuth            int64
Path Width (km)          str
Central Duration         str
dtype: object

In [65]:
solar_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11898 entries, 0 to 11897
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Catalog Number     11898 non-null  int64
 1   Calendar Date      11898 non-null  str
 2   Eclipse Time       11898 non-null  str
 3   Delta T (s)        11898 non-null  int64
 4   Lunation Number    11898 non-null  int64
 5   Saros Number       11898 non-null  int64
 6   Eclipse Type       11898 non-null  str
 7   Gamma              11898 non-null  float64
 8   Eclipse Magnitude  11898 non-null  float64
 9   Latitude           11898 non-null  str
 10  Longitude          11898 non-null  str
 11  Sun Altitude       11898 non-null  int64
 12  Sun Azimuth        11898 non-null  int64
 13  Path Width (km)    7698 non-null   str
 14  Central Duration   7698 non-null   str
dtypes: float64(2), int64(6), str(7)
memory usage: 1.8 MB

In [49]:
solar_df.columns

Index(['Catalog Number', 'Calendar Date', 'Eclipse Time', 'Delta T (s)',
       'Lunation Number', 'Saros Number', 'Eclipse Type', 'Gamma',
       'Eclipse Magnitude', 'Latitude', 'Longitude', 'Sun Altitude',
       'Sun Azimuth', 'Path Width (km)', 'Central Duration'],
      dtype='str')

In [50]:
solar_df.head()

,Catalog Number,Calendar Date,Eclipse Time,Delta T (s),Lunation Number,Saros Number,Eclipse Type,Gamma,Eclipse Magnitude,Latitude,Longitude,Sun Altitude,Sun Azimuth,Path Width (km),Central Duration
0,1,-1999 June 12,03:14:51,46438,-49456,5,T,-0.2701,1.0733,6.0N,33.3W,74,344,247,06m37s
1,2,-1999 December 5,23:45:23,46426,-49450,10,A,-0.2317,0.9382,32.9S,10.8E,76,21,236,06m44s
2,3,-1998 June 1,18:09:16,46415,-49444,15,T,0.4994,1.0284,46.2N,83.4E,60,151,111,02m15s
3,4,-1998 November 25,05:57:03,46403,-49438,20,A,-0.9045,0.9806,67.8S,143.8W,25,74,162,01m14s
4,5,-1997 April 22,13:19:56,46393,-49433,-13,P,-1.4670,0.1611,60.6S,106.4W,0,281,NaN,NaN

In [51]:
solar_df.isna().sum()

Catalog Number          0
Calendar Date           0
Eclipse Time            0
Delta T (s)             0
Lunation Number         0
Saros Number            0
Eclipse Type            0
Gamma                   0
Eclipse Magnitude       0
Latitude                0
Longitude               0
Sun Altitude            0
Sun Azimuth             0
Path Width (km)      4200
Central Duration     4200
dtype: int64

In [64]:
solar_df.describe()

,Catalog Number,Delta T (s),Lunation Number,Saros Number,Gamma,Eclipse Magnitude,Sun Altitude,Sun Azimuth
count,11898.000000,11898.000000,11898.000000,11898.000000,11898.000000,11898.000000,11898.000000,11898.000000
mean,5949.500000,12142.172802,-18546.959321,87.483190,-0.002469,0.812748,36.505295,180.264330
std,3434.801086,13583.402888,17906.572982,48.380284,0.900860,0.300398,32.417350,110.745408
min,1.000000,-6.000000,-49456.000000,-13.000000,-1.569000,0.000000,0.000000,0.000000
25%,2975.250000,970.250000,-33954.750000,47.000000,-0.786575,0.675925,0.000000,89.000000
50%,5949.500000,5636.500000,-18495.000000,87.000000,-0.003850,0.950600,38.000000,180.000000
75%,8923.750000,20943.500000,-3039.250000,128.000000,0.776900,1.018400,66.000000,272.000000
max,11898.000000,46438.000000,12378.000000,190.000000,1.570600,1.081300,90.000000,360.000000

In [53]:
solar_df[solar_df.duplicated()]

Empty DataFrame
Columns: [Catalog Number, Calendar Date, Eclipse Time, Delta T (s), Lunation Number, Saros Number, Eclipse Type, Gamma, Eclipse Magnitude, Latitude, Longitude, Sun Altitude, Sun Azimuth, Path Width (km), Central Duration]
Index: []

In [68]:
solar_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Catalog Number,11898.0,5949.500000,3434.801086,1.000,2975.250000,5949.50000,8923.7500,11898.0000
Delta T (s),11898.0,12142.172802,13583.402888,-6.000,970.250000,5636.50000,20943.5000,46438.0000
Lunation Number,11898.0,-18546.959321,17906.572982,-49456.000,-33954.750000,-18495.00000,-3039.2500,12378.0000
Saros Number,11898.0,87.483190,48.380284,-13.000,47.000000,87.00000,128.0000,190.0000
Gamma,11898.0,-0.002469,0.900860,-1.569,-0.786575,-0.00385,0.7769,1.5706
Eclipse Magnitude,11898.0,0.812748,0.300398,0.000,0.675925,0.95060,1.0184,1.0813
Sun Altitude,11898.0,36.505295,32.417350,0.000,0.000000,38.00000,66.0000,90.0000
Sun Azimuth,11898.0,180.264330,110.745408,0.000,89.000000,180.00000,272.0000,360.0000

## LUNAR DATASET

In [54]:

lunar_df = pd.read_csv(DATA_PATH/"lunar.csv")

lunar_df

,Catalog Number,Calendar Date,Eclipse Time,Delta T (s),Lunation Number,Saros Number,Eclipse Type,Quincena Solar Eclipse,Gamma,Penumbral Magnitude,Umbral Magnitude,Latitude,Longitude,Penumbral Eclipse Duration (m),Partial Eclipse Duration (m),Total Eclipse Duration (m)
0,1,-1999 June 26,14:13:28,46437,-49456,17,N,t-,-1.0981,0.8791,-0.1922,24S,22W,268.8,-,-
1,2,-1999 November 21,20:23:49,46427,-49451,-16,N,-a,-1.1155,0.8143,-0.1921,15N,98W,233.4,-,-
2,3,-1998 May 17,05:47:36,46416,-49445,-11,P,-t,0.8988,1.2105,0.2069,13S,89E,281.7,102.7,-
3,4,-1998 November 11,05:15:58,46404,-49439,-6,P,-a,-0.4644,2.0382,0.9740,12N,113E,343.4,200.8,-
4,5,-1997 May 6,18:57:01,46392,-49433,-1,T+,pp,0.1003,2.6513,1.6963,11S,92W,322.8,213.5,98.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12059,12060,2999 May 21,13:21:13,4417,12360,166,P,t-,0.4971,1.9853,0.9069,20S,178E,356.7,204.2,-
12060,12061,2999 November 14,16:41:25,4421,12366,171,T,a-,-0.4669,1.9868,1.0153,18N,124E,308.0,189.1,18.5
12061,12062,3000 May 10,15:00:16,4424,12372,176,N,t-,1.2117,0.6604,-0.3907,17S,153E,230.6,-,-
12062,12063,3000 October 5,17:10:38,4427,12377,143,Ne,-h,1.5497,0.0329,-1.0039,6N,118E,53.5,-,-
12063,12064,3000 November 4,05:45:18,4428,12378,181,N,h-,-1.2170,0.6326,-0.3828,14N,72W,214.8,-,-

In [55]:
lunar_df.shape

(12064, 16)

In [56]:
lunar_df.dtypes

Catalog Number                      int64
Calendar Date                         str
Eclipse Time                          str
Delta T (s)                         int64
Lunation Number                     int64
Saros Number                        int64
Eclipse Type                          str
Quincena Solar Eclipse                str
Gamma                             float64
Penumbral Magnitude               float64
Umbral Magnitude                  float64
Latitude                              str
Longitude                             str
Penumbral Eclipse Duration (m)    float64
Partial Eclipse Duration (m)          str
Total Eclipse Duration (m)            str
dtype: object

In [57]:
lunar_df.describe()

,Catalog Number,Delta T (s),Lunation Number,Saros Number,Gamma,Penumbral Magnitude,Umbral Magnitude,Penumbral Eclipse Duration (m)
count,12064.000000,12064.000000,12064.000000,12064.000000,12064.000000,12064.000000,12064.000000,12064.000000
mean,6032.500000,12116.476044,-18531.392822,80.505056,0.002490,1.418656,0.400175,269.971941
std,3482.721158,13584.785584,17887.218741,48.416007,0.910505,0.832263,0.832954,79.945444
min,1.000000,-6.000000,-49456.000000,-20.000000,-1.582700,0.000400,-1.095800,5.200000
25%,3016.750000,962.000000,-33923.250000,40.000000,-0.788825,0.684425,-0.334000,223.100000
50%,6032.500000,5597.000000,-18445.500000,80.000000,0.001750,1.417450,0.400450,295.000000
75%,9048.250000,20901.500000,-3067.750000,121.000000,0.791725,2.136900,1.117925,327.800000
max,12064.000000,46437.000000,12378.000000,183.000000,1.579100,2.908900,1.882100,379.500000

In [58]:
lunar_df.columns

Index(['Catalog Number', 'Calendar Date', 'Eclipse Time', 'Delta T (s)',
       'Lunation Number', 'Saros Number', 'Eclipse Type',
       'Quincena Solar Eclipse', 'Gamma', 'Penumbral Magnitude',
       'Umbral Magnitude', 'Latitude', 'Longitude',
       'Penumbral Eclipse Duration (m)', 'Partial Eclipse Duration (m)',
       'Total Eclipse Duration (m)'],
      dtype='str')

In [61]:
lunar_df.head()

,Catalog Number,Calendar Date,Eclipse Time,Delta T (s),Lunation Number,Saros Number,Eclipse Type,Quincena Solar Eclipse,Gamma,Penumbral Magnitude,Umbral Magnitude,Latitude,Longitude,Penumbral Eclipse Duration (m),Partial Eclipse Duration (m),Total Eclipse Duration (m)
0,1,-1999 June 26,14:13:28,46437,-49456,17,N,t-,-1.0981,0.8791,-0.1922,24S,22W,268.8,-,-
1,2,-1999 November 21,20:23:49,46427,-49451,-16,N,-a,-1.1155,0.8143,-0.1921,15N,98W,233.4,-,-
2,3,-1998 May 17,05:47:36,46416,-49445,-11,P,-t,0.8988,1.2105,0.2069,13S,89E,281.7,102.7,-
3,4,-1998 November 11,05:15:58,46404,-49439,-6,P,-a,-0.4644,2.0382,0.9740,12N,113E,343.4,200.8,-
4,5,-1997 May 6,18:57:01,46392,-49433,-1,T+,pp,0.1003,2.6513,1.6963,11S,92W,322.8,213.5,98.2

In [60]:
lunar_df.isna().sum()

Catalog Number                    0
Calendar Date                     0
Eclipse Time                      0
Delta T (s)                       0
Lunation Number                   0
Saros Number                      0
Eclipse Type                      0
Quincena Solar Eclipse            0
Gamma                             0
Penumbral Magnitude               0
Umbral Magnitude                  0
Latitude                          0
Longitude                         0
Penumbral Eclipse Duration (m)    0
Partial Eclipse Duration (m)      0
Total Eclipse Duration (m)        0
dtype: int64

In [62]:
lunar_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12064 entries, 0 to 12063
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Catalog Number                  12064 non-null  int64
 1   Calendar Date                   12064 non-null  str
 2   Eclipse Time                    12064 non-null  str
 3   Delta T (s)                     12064 non-null  int64
 4   Lunation Number                 12064 non-null  int64
 5   Saros Number                    12064 non-null  int64
 6   Eclipse Type                    12064 non-null  str
 7   Quincena Solar Eclipse          12064 non-null  str
 8   Gamma                           12064 non-null  float64
 9   Penumbral Magnitude             12064 non-null  float64
 10  Umbral Magnitude                12064 non-null  float64
 11  Latitude                        12064 non-null  str
 12  Longitude                       12064 non-null  str
 13  Penumbral Eclipse Duration (m)  12064 non-null  float64
 14  Partial Eclipse Duration (m)    12064 non-null  str
 15  Total Eclipse Duration (m)      12064 non-null  str
dtypes: float64(4), int64(4), str(8)
memory usage: 1.9 MB

In [66]:
lunar_df[lunar_df.duplicated()]

Empty DataFrame
Columns: [Catalog Number, Calendar Date, Eclipse Time, Delta T (s), Lunation Number, Saros Number, Eclipse Type, Quincena Solar Eclipse, Gamma, Penumbral Magnitude, Umbral Magnitude, Latitude, Longitude, Penumbral Eclipse Duration (m), Partial Eclipse Duration (m), Total Eclipse Duration (m)]
Index: []

In [67]:
lunar_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Catalog Number,12064.0,6032.500000,3482.721158,1.0000,3016.750000,6032.50000,9048.250000,12064.0000
Delta T (s),12064.0,12116.476044,13584.785584,-6.0000,962.000000,5597.00000,20901.500000,46437.0000
Lunation Number,12064.0,-18531.392822,17887.218741,-49456.0000,-33923.250000,-18445.50000,-3067.750000,12378.0000
Saros Number,12064.0,80.505056,48.416007,-20.0000,40.000000,80.00000,121.000000,183.0000
Gamma,12064.0,0.002490,0.910505,-1.5827,-0.788825,0.00175,0.791725,1.5791
Penumbral Magnitude,12064.0,1.418656,0.832263,0.0004,0.684425,1.41745,2.136900,2.9089
Umbral Magnitude,12064.0,0.400175,0.832954,-1.0958,-0.334000,0.40045,1.117925,1.8821
Penumbral Eclipse Duration (m),12064.0,269.971941,79.945444,5.2000,223.100000,295.00000,327.800000,379.5000